version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      # Amazon API credentials (optional)
      - AMAZON_ACCESS_KEY=${AMAZON_ACCESS_KEY}
      - AMAZON_SECRET_KEY=${AMAZON_SECRET_KEY}
      - AMAZON_PARTNER_TAG=${AMAZON_PARTNER_TAG}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
